///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace JustRecord
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the JustRecordRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("1bfca9a0-eeae-4e4b-a522-e2c1eb3b628b")]
    public partial class JustRecordRepository : RepoGenBaseFolder
    {
        static JustRecordRepository instance = new JustRecordRepository();
        JustRecordRepositoryFolders.ИнформацияAppFolder _информация;
        JustRecordRepositoryFolders.GeoTech3D7ГеологияМаркшейдеAppFolder _geotech3d7геологиямаркшейде;
        JustRecordRepositoryFolders.GeoTechAppFolder _geotech;
        JustRecordRepositoryFolders.GeoTech3DAppFolder _geotech3d;
        JustRecordRepositoryFolders.GeoTech3D1AppFolder _geotech3d1;
        JustRecordRepositoryFolders.GEOTECH3D2AppFolder _geotech3d2;
        JustRecordRepositoryFolders.ОткрытиеAppFolder _открытие;
        JustRecordRepositoryFolders.List1000AppFolder _list1000;
        JustRecordRepositoryFolders.GEOTECH3D3AppFolder _geotech3d3;
        JustRecordRepositoryFolders.GEOTECH3D4AppFolder _geotech3d4;

        /// <summary>
        /// Gets the singleton class instance representing the JustRecordRepository element repository.
        /// </summary>
        [RepositoryFolder("1bfca9a0-eeae-4e4b-a522-e2c1eb3b628b")]
        public static JustRecordRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public JustRecordRepository() 
            : base("JustRecordRepository", "/", null, 0, false, "1bfca9a0-eeae-4e4b-a522-e2c1eb3b628b", ".\\RepositoryImages\\JustRecordRepository1bfca9a0.rximgres")
        {
            _информация = new JustRecordRepositoryFolders.ИнформацияAppFolder(this);
            _geotech3d7геологиямаркшейде = new JustRecordRepositoryFolders.GeoTech3D7ГеологияМаркшейдеAppFolder(this);
            _geotech = new JustRecordRepositoryFolders.GeoTechAppFolder(this);
            _geotech3d = new JustRecordRepositoryFolders.GeoTech3DAppFolder(this);
            _geotech3d1 = new JustRecordRepositoryFolders.GeoTech3D1AppFolder(this);
            _geotech3d2 = new JustRecordRepositoryFolders.GEOTECH3D2AppFolder(this);
            _открытие = new JustRecordRepositoryFolders.ОткрытиеAppFolder(this);
            _list1000 = new JustRecordRepositoryFolders.List1000AppFolder(this);
            _geotech3d3 = new JustRecordRepositoryFolders.GEOTECH3D3AppFolder(this);
            _geotech3d4 = new JustRecordRepositoryFolders.GEOTECH3D4AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("1bfca9a0-eeae-4e4b-a522-e2c1eb3b628b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Информация folder.
        /// </summary>
        [RepositoryFolder("d093b2e7-4e76-4907-b0ee-9230be9db716")]
        public virtual JustRecordRepositoryFolders.ИнформацияAppFolder Информация
        {
            get { return _информация; }
        }

        /// <summary>
        /// The GeoTech3D7ГеологияМаркшейде folder.
        /// </summary>
        [RepositoryFolder("a19d02ab-875e-4b4a-90d5-3e22de78f373")]
        public virtual JustRecordRepositoryFolders.GeoTech3D7ГеологияМаркшейдеAppFolder GeoTech3D7ГеологияМаркшейде
        {
            get { return _geotech3d7геологиямаркшейде; }
        }

        /// <summary>
        /// The GeoTech folder.
        /// </summary>
        [RepositoryFolder("4af80a55-f5f9-46f3-aa4c-76dfebf4ce51")]
        public virtual JustRecordRepositoryFolders.GeoTechAppFolder GeoTech
        {
            get { return _geotech; }
        }

        /// <summary>
        /// The GeoTech3D folder.
        /// </summary>
        [RepositoryFolder("51e964e6-9a19-4ac4-a386-e49f5df5a1d0")]
        public virtual JustRecordRepositoryFolders.GeoTech3DAppFolder GeoTech3D
        {
            get { return _geotech3d; }
        }

        /// <summary>
        /// The GeoTech3D1 folder.
        /// </summary>
        [RepositoryFolder("d410ddd6-cd35-47f2-aed0-d5812134c4b3")]
        public virtual JustRecordRepositoryFolders.GeoTech3D1AppFolder GeoTech3D1
        {
            get { return _geotech3d1; }
        }

        /// <summary>
        /// The GEOTECH3D2 folder.
        /// </summary>
        [RepositoryFolder("53c32ea7-780e-46f7-89f5-f741cdacfaaa")]
        public virtual JustRecordRepositoryFolders.GEOTECH3D2AppFolder GEOTECH3D2
        {
            get { return _geotech3d2; }
        }

        /// <summary>
        /// The Открытие folder.
        /// </summary>
        [RepositoryFolder("78a9c7f2-0cb3-4ff7-9f02-cd5398d10bd0")]
        public virtual JustRecordRepositoryFolders.ОткрытиеAppFolder Открытие
        {
            get { return _открытие; }
        }

        /// <summary>
        /// The List1000 folder.
        /// </summary>
        [RepositoryFolder("3b36df56-ea40-4f3b-8794-e9b13f17e22e")]
        public virtual JustRecordRepositoryFolders.List1000AppFolder List1000
        {
            get { return _list1000; }
        }

        /// <summary>
        /// The GEOTECH3D3 folder.
        /// </summary>
        [RepositoryFolder("81f1c77d-477b-4eb4-b6db-adf3a0990f21")]
        public virtual JustRecordRepositoryFolders.GEOTECH3D3AppFolder GEOTECH3D3
        {
            get { return _geotech3d3; }
        }

        /// <summary>
        /// The GEOTECH3D4 folder.
        /// </summary>
        [RepositoryFolder("a0f198ba-0d50-4dff-af86-fa564e0e277a")]
        public virtual JustRecordRepositoryFolders.GEOTECH3D4AppFolder GEOTECH3D4
        {
            get { return _geotech3d4; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class JustRecordRepositoryFolders
    {
        /// <summary>
        /// The ИнформацияAppFolder folder.
        /// </summary>
        [RepositoryFolder("d093b2e7-4e76-4907-b0ee-9230be9db716")]
        public partial class ИнформацияAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonокInfo;

            /// <summary>
            /// Creates a new Информация  folder.
            /// </summary>
            public ИнформацияAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Информация", "/form[@title='Информация']", parentFolder, 30000, null, true, "d093b2e7-4e76-4907-b0ee-9230be9db716", "")
            {
                _buttonокInfo = new RepoItemInfo(this, "ButtonОК", "?/?/element[@instance='0']/button[@text='О&К']", 30000, null, "45349417-9fd4-443e-8982-fb83eb077132");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d093b2e7-4e76-4907-b0ee-9230be9db716")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d093b2e7-4e76-4907-b0ee-9230be9db716")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonОК item.
            /// </summary>
            [RepositoryItem("45349417-9fd4-443e-8982-fb83eb077132")]
            public virtual Ranorex.Button ButtonОК
            {
                get
                {
                    return _buttonокInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonОК item info.
            /// </summary>
            [RepositoryItemInfo("45349417-9fd4-443e-8982-fb83eb077132")]
            public virtual RepoItemInfo ButtonОКInfo
            {
                get
                {
                    return _buttonокInfo;
                }
            }
        }

        /// <summary>
        /// The GeoTech3D7ГеологияМаркшейдеAppFolder folder.
        /// </summary>
        [RepositoryFolder("a19d02ab-875e-4b4a-90d5-3e22de78f373")]
        public partial class GeoTech3D7ГеологияМаркшейдеAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _символInfo;
            RepoItemInfo _someelementInfo;
            RepoItemInfo _objinspInfo;
            RepoItemInfo _propokbtnInfo;
            RepoItemInfo _form65280Info;
            RepoItemInfo _someelement1Info;
            RepoItemInfo _действияInfo;
            RepoItemInfo _закрытьInfo;

            /// <summary>
            /// Creates a new GeoTech3D7ГеологияМаркшейде  folder.
            /// </summary>
            public GeoTech3D7ГеологияМаркшейдеAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GeoTech3D7ГеологияМаркшейде", "/form[@name='MainForm' and @title~'^GeoTech-3D\\ 7\\ \\|\\ \\ \\ \\ \\ \\ \\ \\ Гео']", parentFolder, 30000, null, true, "a19d02ab-875e-4b4a-90d5-3e22de78f373", "")
            {
                _символInfo = new RepoItemInfo(this, "Символ", "?/?/menuitem[@name='SymbolItm']", 30000, null, "361fe127-8a7c-4b85-901c-5616fd7d713f");
                _someelementInfo = new RepoItemInfo(this, "SomeElement", "element[@name='LeftControlBar']/form[@title='Объекты']/element[1]", 30000, null, "5f22cfdf-2745-4ad5-a0f8-b1779a8ae78c");
                _objinspInfo = new RepoItemInfo(this, "ObjInsp", "container[@name='LeftDockPanel']/form[@name='OKBottomDlg']/?/?/container[@name='PropertyTab']//tree[@name='ObjInsp']", 30000, null, "4251c7a8-7677-4283-a419-36825100636b");
                _propokbtnInfo = new RepoItemInfo(this, "PropOkBtn", "container[@name='LeftDockPanel']/form[@name='OKBottomDlg']//element[@name='PropOkBtn']", 30000, null, "9ab17bd3-7113-4afc-b3d6-fa294cbedfc2");
                _form65280Info = new RepoItemInfo(this, "Form65280", "form[@name='MDIChild']", 30000, null, "bd1422ff-c184-445b-8cfd-8437af371d2c");
                _someelement1Info = new RepoItemInfo(this, "SomeElement1", "element[@name='LeftControlBar']/form[@title='Редактирование']/element[5]", 30000, null, "d8dc9298-936e-4e27-ba88-8fa253c53dbb");
                _действияInfo = new RepoItemInfo(this, "Действия", "?/?/menuitem[@name='miMainActions']", 30000, null, "7597c3ae-159b-4114-b811-f41459b37df8");
                _закрытьInfo = new RepoItemInfo(this, "Закрыть", "?/?/button[@accessiblename='Закрыть']", 30000, null, "13561c1e-17ab-4eb3-9bbd-c1ba6818ce17");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a19d02ab-875e-4b4a-90d5-3e22de78f373")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a19d02ab-875e-4b4a-90d5-3e22de78f373")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Символ item.
            /// </summary>
            [RepositoryItem("361fe127-8a7c-4b85-901c-5616fd7d713f")]
            public virtual Ranorex.MenuItem Символ
            {
                get
                {
                    return _символInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Символ item info.
            /// </summary>
            [RepositoryItemInfo("361fe127-8a7c-4b85-901c-5616fd7d713f")]
            public virtual RepoItemInfo СимволInfo
            {
                get
                {
                    return _символInfo;
                }
            }

            /// <summary>
            /// The SomeElement item.
            /// </summary>
            [RepositoryItem("5f22cfdf-2745-4ad5-a0f8-b1779a8ae78c")]
            public virtual Ranorex.Unknown SomeElement
            {
                get
                {
                    return _someelementInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement item info.
            /// </summary>
            [RepositoryItemInfo("5f22cfdf-2745-4ad5-a0f8-b1779a8ae78c")]
            public virtual RepoItemInfo SomeElementInfo
            {
                get
                {
                    return _someelementInfo;
                }
            }

            /// <summary>
            /// The ObjInsp item.
            /// </summary>
            [RepositoryItem("4251c7a8-7677-4283-a419-36825100636b")]
            public virtual Ranorex.Tree ObjInsp
            {
                get
                {
                    return _objinspInfo.CreateAdapter<Ranorex.Tree>(true);
                }
            }

            /// <summary>
            /// The ObjInsp item info.
            /// </summary>
            [RepositoryItemInfo("4251c7a8-7677-4283-a419-36825100636b")]
            public virtual RepoItemInfo ObjInspInfo
            {
                get
                {
                    return _objinspInfo;
                }
            }

            /// <summary>
            /// The PropOkBtn item.
            /// </summary>
            [RepositoryItem("9ab17bd3-7113-4afc-b3d6-fa294cbedfc2")]
            public virtual Ranorex.Unknown PropOkBtn
            {
                get
                {
                    return _propokbtnInfo.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The PropOkBtn item info.
            /// </summary>
            [RepositoryItemInfo("9ab17bd3-7113-4afc-b3d6-fa294cbedfc2")]
            public virtual RepoItemInfo PropOkBtnInfo
            {
                get
                {
                    return _propokbtnInfo;
                }
            }

            /// <summary>
            /// The Form65280 item.
            /// </summary>
            [RepositoryItem("bd1422ff-c184-445b-8cfd-8437af371d2c")]
            public virtual Ranorex.Form Form65280
            {
                get
                {
                    return _form65280Info.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Form65280 item info.
            /// </summary>
            [RepositoryItemInfo("bd1422ff-c184-445b-8cfd-8437af371d2c")]
            public virtual RepoItemInfo Form65280Info
            {
                get
                {
                    return _form65280Info;
                }
            }

            /// <summary>
            /// The SomeElement1 item.
            /// </summary>
            [RepositoryItem("d8dc9298-936e-4e27-ba88-8fa253c53dbb")]
            public virtual Ranorex.Unknown SomeElement1
            {
                get
                {
                    return _someelement1Info.CreateAdapter<Ranorex.Unknown>(true);
                }
            }

            /// <summary>
            /// The SomeElement1 item info.
            /// </summary>
            [RepositoryItemInfo("d8dc9298-936e-4e27-ba88-8fa253c53dbb")]
            public virtual RepoItemInfo SomeElement1Info
            {
                get
                {
                    return _someelement1Info;
                }
            }

            /// <summary>
            /// The Действия item.
            /// </summary>
            [RepositoryItem("7597c3ae-159b-4114-b811-f41459b37df8")]
            public virtual Ranorex.MenuItem Действия
            {
                get
                {
                    return _действияInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Действия item info.
            /// </summary>
            [RepositoryItemInfo("7597c3ae-159b-4114-b811-f41459b37df8")]
            public virtual RepoItemInfo ДействияInfo
            {
                get
                {
                    return _действияInfo;
                }
            }

            /// <summary>
            /// The Закрыть item.
            /// </summary>
            [RepositoryItem("13561c1e-17ab-4eb3-9bbd-c1ba6818ce17")]
            public virtual Ranorex.Button Закрыть
            {
                get
                {
                    return _закрытьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Закрыть item info.
            /// </summary>
            [RepositoryItemInfo("13561c1e-17ab-4eb3-9bbd-c1ba6818ce17")]
            public virtual RepoItemInfo ЗакрытьInfo
            {
                get
                {
                    return _закрытьInfo;
                }
            }
        }

        /// <summary>
        /// The GeoTechAppFolder folder.
        /// </summary>
        [RepositoryFolder("4af80a55-f5f9-46f3-aa4c-76dfebf4ce51")]
        public partial class GeoTechAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _создатьctrlplusnInfo;
            RepoItemInfo _импортизфайлаInfo;

            /// <summary>
            /// Creates a new GeoTech  folder.
            /// </summary>
            public GeoTechAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GeoTech", "/contextmenu[@processname='GeoTech']", parentFolder, 30000, null, false, "4af80a55-f5f9-46f3-aa4c-76dfebf4ce51", "")
            {
                _создатьctrlplusnInfo = new RepoItemInfo(this, "СоздатьCtrlPlusN", "?/?/menuitem[@accessiblename='Создать...Ctrl+N']", 30000, null, "90597f32-768d-4c37-85ab-1324d0fd2166");
                _импортизфайлаInfo = new RepoItemInfo(this, "ИмпортИзФайла", "?/?/menuitem[@accessiblename='Импорт из файла']", 30000, null, "c5fb4ff3-aef3-4aeb-86fa-a2bbac0553ac");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4af80a55-f5f9-46f3-aa4c-76dfebf4ce51")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4af80a55-f5f9-46f3-aa4c-76dfebf4ce51")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The СоздатьCtrlPlusN item.
            /// </summary>
            [RepositoryItem("90597f32-768d-4c37-85ab-1324d0fd2166")]
            public virtual Ranorex.MenuItem СоздатьCtrlPlusN
            {
                get
                {
                    return _создатьctrlplusnInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The СоздатьCtrlPlusN item info.
            /// </summary>
            [RepositoryItemInfo("90597f32-768d-4c37-85ab-1324d0fd2166")]
            public virtual RepoItemInfo СоздатьCtrlPlusNInfo
            {
                get
                {
                    return _создатьctrlplusnInfo;
                }
            }

            /// <summary>
            /// The ИмпортИзФайла item.
            /// </summary>
            [RepositoryItem("c5fb4ff3-aef3-4aeb-86fa-a2bbac0553ac")]
            public virtual Ranorex.MenuItem ИмпортИзФайла
            {
                get
                {
                    return _импортизфайлаInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The ИмпортИзФайла item info.
            /// </summary>
            [RepositoryItemInfo("c5fb4ff3-aef3-4aeb-86fa-a2bbac0553ac")]
            public virtual RepoItemInfo ИмпортИзФайлаInfo
            {
                get
                {
                    return _импортизфайлаInfo;
                }
            }
        }

        /// <summary>
        /// The GeoTech3DAppFolder folder.
        /// </summary>
        [RepositoryFolder("51e964e6-9a19-4ac4-a386-e49f5df5a1d0")]
        public partial class GeoTech3DAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _sbtcreateprojectInfo;

            /// <summary>
            /// Creates a new GeoTech3D  folder.
            /// </summary>
            public GeoTech3DAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GeoTech3D", "/form[@name='DualListDlg']", parentFolder, 30000, null, true, "51e964e6-9a19-4ac4-a386-e49f5df5a1d0", "")
            {
                _sbtcreateprojectInfo = new RepoItemInfo(this, "SbtCreateProject", "button[@name='sbtCreateProject']", 30000, null, "c3ed079b-ebda-405b-ad78-ff98a18f479b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("51e964e6-9a19-4ac4-a386-e49f5df5a1d0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("51e964e6-9a19-4ac4-a386-e49f5df5a1d0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SbtCreateProject item.
            /// </summary>
            [RepositoryItem("c3ed079b-ebda-405b-ad78-ff98a18f479b")]
            public virtual Ranorex.Button SbtCreateProject
            {
                get
                {
                    return _sbtcreateprojectInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The SbtCreateProject item info.
            /// </summary>
            [RepositoryItemInfo("c3ed079b-ebda-405b-ad78-ff98a18f479b")]
            public virtual RepoItemInfo SbtCreateProjectInfo
            {
                get
                {
                    return _sbtcreateprojectInfo;
                }
            }
        }

        /// <summary>
        /// The GeoTech3D1AppFolder folder.
        /// </summary>
        [RepositoryFolder("d410ddd6-cd35-47f2-aed0-d5812134c4b3")]
        public partial class GeoTech3D1AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _применитьInfo;

            /// <summary>
            /// Creates a new GeoTech3D1  folder.
            /// </summary>
            public GeoTech3D1AppFolder(RepoGenBaseFolder parentFolder) :
                    base("GeoTech3D1", "/form[@name='NewNameProj']", parentFolder, 30000, null, true, "d410ddd6-cd35-47f2-aed0-d5812134c4b3", "")
            {
                _применитьInfo = new RepoItemInfo(this, "Применить", "button[@name='btnApply']", 30000, null, "237a6f4b-25f1-47b6-8460-8baba1268bf6");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d410ddd6-cd35-47f2-aed0-d5812134c4b3")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d410ddd6-cd35-47f2-aed0-d5812134c4b3")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Применить item.
            /// </summary>
            [RepositoryItem("237a6f4b-25f1-47b6-8460-8baba1268bf6")]
            public virtual Ranorex.Button Применить
            {
                get
                {
                    return _применитьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Применить item info.
            /// </summary>
            [RepositoryItemInfo("237a6f4b-25f1-47b6-8460-8baba1268bf6")]
            public virtual RepoItemInfo ПрименитьInfo
            {
                get
                {
                    return _применитьInfo;
                }
            }
        }

        /// <summary>
        /// The GEOTECH3D2AppFolder folder.
        /// </summary>
        [RepositoryFolder("53c32ea7-780e-46f7-89f5-f741cdacfaaa")]
        public partial class GEOTECH3D2AppFolder : RepoGenBaseFolder
        {
            JustRecordRepositoryFolders.TabbedNotebook1Folder _tabbednotebook1;
            RepoItemInfo _выполнитьInfo;

            /// <summary>
            /// Creates a new GEOTECH3D2  folder.
            /// </summary>
            public GEOTECH3D2AppFolder(RepoGenBaseFolder parentFolder) :
                    base("GEOTECH3D2", "/form[@name='GeoOptions']", parentFolder, 30000, null, true, "53c32ea7-780e-46f7-89f5-f741cdacfaaa", "")
            {
                _tabbednotebook1 = new JustRecordRepositoryFolders.TabbedNotebook1Folder(this);
                _выполнитьInfo = new RepoItemInfo(this, "Выполнить", "button[@name='OKBtn']", 30000, null, "671912ae-7a90-481a-967d-f89ddbdba2c7");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("53c32ea7-780e-46f7-89f5-f741cdacfaaa")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("53c32ea7-780e-46f7-89f5-f741cdacfaaa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Выполнить item.
            /// </summary>
            [RepositoryItem("671912ae-7a90-481a-967d-f89ddbdba2c7")]
            public virtual Ranorex.Button Выполнить
            {
                get
                {
                    return _выполнитьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Выполнить item info.
            /// </summary>
            [RepositoryItemInfo("671912ae-7a90-481a-967d-f89ddbdba2c7")]
            public virtual RepoItemInfo ВыполнитьInfo
            {
                get
                {
                    return _выполнитьInfo;
                }
            }

            /// <summary>
            /// The TabbedNotebook1 folder.
            /// </summary>
            [RepositoryFolder("74d32fb2-669d-4555-b90f-61af041f6d43")]
            public virtual JustRecordRepositoryFolders.TabbedNotebook1Folder TabbedNotebook1
            {
                get { return _tabbednotebook1; }
            }
        }

        /// <summary>
        /// The TabbedNotebook1Folder folder.
        /// </summary>
        [RepositoryFolder("74d32fb2-669d-4555-b90f-61af041f6d43")]
        public partial class TabbedNotebook1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _xmaxeditInfo;
            RepoItemInfo _xmineditInfo;
            RepoItemInfo _ymaxeditInfo;
            RepoItemInfo _ymineditInfo;

            /// <summary>
            /// Creates a new TabbedNotebook1  folder.
            /// </summary>
            public TabbedNotebook1Folder(RepoGenBaseFolder parentFolder) :
                    base("TabbedNotebook1", "tabpagelist[@name='TabbedNotebook1']", parentFolder, 30000, null, false, "74d32fb2-669d-4555-b90f-61af041f6d43", "")
            {
                _xmaxeditInfo = new RepoItemInfo(this, "XmaxEdit", ".//text[@name='XmaxEdit']", 30000, null, "1baa70e9-5782-4474-8c1f-cbcafcd9400a");
                _xmineditInfo = new RepoItemInfo(this, "XminEdit", ".//text[@name='XminEdit']", 30000, null, "156cdbd3-8e9f-4c51-9f50-bae68bae7ca5");
                _ymaxeditInfo = new RepoItemInfo(this, "YmaxEdit", ".//text[@name='YmaxEdit']", 30000, null, "10842411-4604-48ab-8f94-1af0b4299ba6");
                _ymineditInfo = new RepoItemInfo(this, "YminEdit", ".//text[@name='YminEdit']", 30000, null, "db754ab5-fbb7-4bd8-bb04-52246f3b470c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("74d32fb2-669d-4555-b90f-61af041f6d43")]
            public virtual Ranorex.TabPageList Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.TabPageList>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("74d32fb2-669d-4555-b90f-61af041f6d43")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The XmaxEdit item.
            /// </summary>
            [RepositoryItem("1baa70e9-5782-4474-8c1f-cbcafcd9400a")]
            public virtual Ranorex.Text XmaxEdit
            {
                get
                {
                    return _xmaxeditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The XmaxEdit item info.
            /// </summary>
            [RepositoryItemInfo("1baa70e9-5782-4474-8c1f-cbcafcd9400a")]
            public virtual RepoItemInfo XmaxEditInfo
            {
                get
                {
                    return _xmaxeditInfo;
                }
            }

            /// <summary>
            /// The XminEdit item.
            /// </summary>
            [RepositoryItem("156cdbd3-8e9f-4c51-9f50-bae68bae7ca5")]
            public virtual Ranorex.Text XminEdit
            {
                get
                {
                    return _xmineditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The XminEdit item info.
            /// </summary>
            [RepositoryItemInfo("156cdbd3-8e9f-4c51-9f50-bae68bae7ca5")]
            public virtual RepoItemInfo XminEditInfo
            {
                get
                {
                    return _xmineditInfo;
                }
            }

            /// <summary>
            /// The YmaxEdit item.
            /// </summary>
            [RepositoryItem("10842411-4604-48ab-8f94-1af0b4299ba6")]
            public virtual Ranorex.Text YmaxEdit
            {
                get
                {
                    return _ymaxeditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The YmaxEdit item info.
            /// </summary>
            [RepositoryItemInfo("10842411-4604-48ab-8f94-1af0b4299ba6")]
            public virtual RepoItemInfo YmaxEditInfo
            {
                get
                {
                    return _ymaxeditInfo;
                }
            }

            /// <summary>
            /// The YminEdit item.
            /// </summary>
            [RepositoryItem("db754ab5-fbb7-4bd8-bb04-52246f3b470c")]
            public virtual Ranorex.Text YminEdit
            {
                get
                {
                    return _ymineditInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The YminEdit item info.
            /// </summary>
            [RepositoryItemInfo("db754ab5-fbb7-4bd8-bb04-52246f3b470c")]
            public virtual RepoItemInfo YminEditInfo
            {
                get
                {
                    return _ymineditInfo;
                }
            }
        }

        /// <summary>
        /// The ОткрытиеAppFolder folder.
        /// </summary>
        [RepositoryFolder("78a9c7f2-0cb3-4ff7-9f02-cd5398d10bd0")]
        public partial class ОткрытиеAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _combobox1136Info;
            RepoItemInfo _systemitemnamedisplayInfo;
            RepoItemInfo _buttonоткрытьInfo;

            /// <summary>
            /// Creates a new Открытие  folder.
            /// </summary>
            public ОткрытиеAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Открытие", "/form[@title='Открытие']", parentFolder, 30000, null, true, "78a9c7f2-0cb3-4ff7-9f02-cd5398d10bd0", "")
            {
                _combobox1136Info = new RepoItemInfo(this, "ComboBox1136", "combobox[@controlid='1136']", 30000, null, "11db4a33-fd28-462a-ad3a-4c2cca1fa9e3");
                _systemitemnamedisplayInfo = new RepoItemInfo(this, "SystemItemNameDisplay", "element[@class='DUIViewWndClassName']//container[@caption='ShellView']/?/?/listitem[@automationid='1']/text[@automationid='System.ItemNameDisplay']", 30000, null, "76b11e61-4c78-45e2-b8bb-14c32e090c6d");
                _buttonоткрытьInfo = new RepoItemInfo(this, "ButtonОткрыть", "button[@text='&Открыть']", 30000, null, "aa1cc70c-01ef-433a-b11c-db9760ac9df5");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("78a9c7f2-0cb3-4ff7-9f02-cd5398d10bd0")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("78a9c7f2-0cb3-4ff7-9f02-cd5398d10bd0")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ComboBox1136 item.
            /// </summary>
            [RepositoryItem("11db4a33-fd28-462a-ad3a-4c2cca1fa9e3")]
            public virtual Ranorex.ComboBox ComboBox1136
            {
                get
                {
                    return _combobox1136Info.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox1136 item info.
            /// </summary>
            [RepositoryItemInfo("11db4a33-fd28-462a-ad3a-4c2cca1fa9e3")]
            public virtual RepoItemInfo ComboBox1136Info
            {
                get
                {
                    return _combobox1136Info;
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item.
            /// </summary>
            [RepositoryItem("76b11e61-4c78-45e2-b8bb-14c32e090c6d")]
            public virtual Ranorex.Text SystemItemNameDisplay
            {
                get
                {
                    return _systemitemnamedisplayInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The SystemItemNameDisplay item info.
            /// </summary>
            [RepositoryItemInfo("76b11e61-4c78-45e2-b8bb-14c32e090c6d")]
            public virtual RepoItemInfo SystemItemNameDisplayInfo
            {
                get
                {
                    return _systemitemnamedisplayInfo;
                }
            }

            /// <summary>
            /// The ButtonОткрыть item.
            /// </summary>
            [RepositoryItem("aa1cc70c-01ef-433a-b11c-db9760ac9df5")]
            public virtual Ranorex.Button ButtonОткрыть
            {
                get
                {
                    return _buttonоткрытьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonОткрыть item info.
            /// </summary>
            [RepositoryItemInfo("aa1cc70c-01ef-433a-b11c-db9760ac9df5")]
            public virtual RepoItemInfo ButtonОткрытьInfo
            {
                get
                {
                    return _buttonоткрытьInfo;
                }
            }
        }

        /// <summary>
        /// The List1000AppFolder folder.
        /// </summary>
        [RepositoryFolder("3b36df56-ea40-4f3b-8794-e9b13f17e22e")]
        public partial class List1000AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _файлыautocad2004dxfasteriskdxfInfo;

            /// <summary>
            /// Creates a new List1000  folder.
            /// </summary>
            public List1000AppFolder(RepoGenBaseFolder parentFolder) :
                    base("List1000", "/list[@controlid='1000']", parentFolder, 30000, null, true, "3b36df56-ea40-4f3b-8794-e9b13f17e22e", "")
            {
                _файлыautocad2004dxfasteriskdxfInfo = new RepoItemInfo(this, "ФайлыAutoCAD2004DXFAsteriskDxf", "listitem[@text~'^Файлы\\ AutoCAD\\ 2004\\ DXF\\ \\(\\*']", 30000, null, "95879847-5bed-48a7-9f12-953c58262382");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("3b36df56-ea40-4f3b-8794-e9b13f17e22e")]
            public virtual Ranorex.List Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.List>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("3b36df56-ea40-4f3b-8794-e9b13f17e22e")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ФайлыAutoCAD2004DXFAsteriskDxf item.
            /// </summary>
            [RepositoryItem("95879847-5bed-48a7-9f12-953c58262382")]
            public virtual Ranorex.ListItem ФайлыAutoCAD2004DXFAsteriskDxf
            {
                get
                {
                    return _файлыautocad2004dxfasteriskdxfInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The ФайлыAutoCAD2004DXFAsteriskDxf item info.
            /// </summary>
            [RepositoryItemInfo("95879847-5bed-48a7-9f12-953c58262382")]
            public virtual RepoItemInfo ФайлыAutoCAD2004DXFAsteriskDxfInfo
            {
                get
                {
                    return _файлыautocad2004dxfasteriskdxfInfo;
                }
            }
        }

        /// <summary>
        /// The GEOTECH3D3AppFolder folder.
        /// </summary>
        [RepositoryFolder("81f1c77d-477b-4eb4-b6db-adf3a0990f21")]
        public partial class GEOTECH3D3AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _геодезическиеInfo;
            RepoItemInfo _импортInfo;

            /// <summary>
            /// Creates a new GEOTECH3D3  folder.
            /// </summary>
            public GEOTECH3D3AppFolder(RepoGenBaseFolder parentFolder) :
                    base("GEOTECH3D3", "/form[@name='ImportDXFOption']", parentFolder, 30000, null, true, "81f1c77d-477b-4eb4-b6db-adf3a0990f21", "")
            {
                _геодезическиеInfo = new RepoItemInfo(this, "Геодезические", "?/?/radiobutton[@name='rbGeod']", 30000, null, "fdd384f0-16a6-4c16-8f63-828266ea9d0c");
                _импортInfo = new RepoItemInfo(this, "Импорт", "button[@name='btnOK']", 30000, null, "1c88fe62-4297-4852-b077-022eb4dc600f");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("81f1c77d-477b-4eb4-b6db-adf3a0990f21")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("81f1c77d-477b-4eb4-b6db-adf3a0990f21")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Геодезические item.
            /// </summary>
            [RepositoryItem("fdd384f0-16a6-4c16-8f63-828266ea9d0c")]
            public virtual Ranorex.RadioButton Геодезические
            {
                get
                {
                    return _геодезическиеInfo.CreateAdapter<Ranorex.RadioButton>(true);
                }
            }

            /// <summary>
            /// The Геодезические item info.
            /// </summary>
            [RepositoryItemInfo("fdd384f0-16a6-4c16-8f63-828266ea9d0c")]
            public virtual RepoItemInfo ГеодезическиеInfo
            {
                get
                {
                    return _геодезическиеInfo;
                }
            }

            /// <summary>
            /// The Импорт item.
            /// </summary>
            [RepositoryItem("1c88fe62-4297-4852-b077-022eb4dc600f")]
            public virtual Ranorex.Button Импорт
            {
                get
                {
                    return _импортInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Импорт item info.
            /// </summary>
            [RepositoryItemInfo("1c88fe62-4297-4852-b077-022eb4dc600f")]
            public virtual RepoItemInfo ИмпортInfo
            {
                get
                {
                    return _импортInfo;
                }
            }
        }

        /// <summary>
        /// The GEOTECH3D4AppFolder folder.
        /// </summary>
        [RepositoryFolder("a0f198ba-0d50-4dff-af86-fa564e0e277a")]
        public partial class GEOTECH3D4AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _продолжитьInfo;

            /// <summary>
            /// Creates a new GEOTECH3D4  folder.
            /// </summary>
            public GEOTECH3D4AppFolder(RepoGenBaseFolder parentFolder) :
                    base("GEOTECH3D4", "/form[@name='frmImportDxfShift']", parentFolder, 30000, null, true, "a0f198ba-0d50-4dff-af86-fa564e0e277a", "")
            {
                _продолжитьInfo = new RepoItemInfo(this, "Продолжить", "button[@name='Button1']", 30000, null, "15188fa3-d2a7-4ef9-b869-50e12c618b5a");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a0f198ba-0d50-4dff-af86-fa564e0e277a")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a0f198ba-0d50-4dff-af86-fa564e0e277a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Продолжить item.
            /// </summary>
            [RepositoryItem("15188fa3-d2a7-4ef9-b869-50e12c618b5a")]
            public virtual Ranorex.Button Продолжить
            {
                get
                {
                    return _продолжитьInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Продолжить item info.
            /// </summary>
            [RepositoryItemInfo("15188fa3-d2a7-4ef9-b869-50e12c618b5a")]
            public virtual RepoItemInfo ПродолжитьInfo
            {
                get
                {
                    return _продолжитьInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}